test cbss record
Uncomment and update steps for processing XML files, converting to HTML, and uploading to S3.

diff --git a/.github/workflows/batch_loading.yml b/.github/workflows/batch_loading.yml
--- a/.github/workflows/batch_loading.yml
+++ b/.github/workflows/batch_loading.yml
@@ -49,7 +49,7 @@ jobs:
       - name: Identify XML files
         run: |
           # Find each section of data for processing one at a time, or target files
-          find ./data/works/tei -name '*.xml' | head -n 5000 > xml_files.txt
+          # find ./data/works/tei -name '*.xml' | head -n 5000 > xml_files.txt
           # find ./data/places/tei -name '*.xml' > xml_files.txt
           # find ./data/persons/tei -name '*.xml' > xml_files.txt
           # Bibliographic records should be run in batches of 5000
@@ -62,7 +62,7 @@ jobs:
           # head -n 30000 all_files.txt | tail -n 5000 > xml_files.txt
 
           # find ./data/taxonomy -name '*.rdf' > xml_files.txt
-
+          
           # test cases
           # JoE
           # echo "./data/places/tei/5622.xml" > xml_files.txt
@@ -89,6 +89,7 @@ jobs:
           # echo "./data/bibl/tei/NS3SCJLY.xml" >> xml_files.txt
           # echo "./data/bibl/tei/NZZP9CTH.xml" >> xml_files.txt
 
+          echo "./data/bibl/tei/AN7M765U.xml" > xml_files.txt
 
 
           echo "Processing $(wc -l < xml_files.txt) XML files"
@@ -170,102 +171,102 @@ jobs:
           git diff --cached --quiet || git commit -m "Update index_12_works.json"
           git push
 
-      # # Step 7: Convert XML to HTML in Parallel For Website pages
-      # - name: Convert XML to HTML in Parallel (with syriacadata path)
-      #   run: |
-      #     mkdir -p logs
+      # Step 7: Convert XML to HTML in Parallel For Website pages
+      - name: Convert XML to HTML in Parallel (with syriacadata path)
+        run: |
+          mkdir -p logs
       
-      #     cat xml_files.txt | xargs -P $(nproc) -I {} sh -c '
-      #       file="$1"
-      #       filename=$(basename "${file%.xml}")
+          cat xml_files.txt | xargs -P $(nproc) -I {} sh -c '
+            file="$1"
+            filename=$(basename "${file%.xml}")
       
-      #       # Final output path
-      #       out_dir="data-html/syriacadata/$(dirname "$filename")"
-      #       mkdir -p "$out_dir"
+            # Final output path
+            out_dir="data-html/syriacadata/$(dirname "$filename")"
+            mkdir -p "$out_dir"
       
-      #       echo "Converting $file → $out_dir/$filename.html"
-      #       if ! java -jar saxon.jar -s:"$file" -xsl:html-stylesheet.xsl -o:"$out_dir/$filename.html" 2>> logs/errors.log; then
-      #         echo "::warning:: HTML transformation failed for $file"
-      #         echo "Error processing $file" >> logs/errors.log
-      #       fi
-      #     ' sh {}
+            echo "Converting $file → $out_dir/$filename.html"
+            if ! java -jar saxon.jar -s:"$file" -xsl:html-stylesheet.xsl -o:"$out_dir/$filename.html" 2>> logs/errors.log; then
+              echo "::warning:: HTML transformation failed for $file"
+              echo "Error processing $file" >> logs/errors.log
+            fi
+          ' sh {}
           
-      # # Step 8: Upload HTML files to S3 
+      # Step 8: Upload HTML files to S3 
       
-      # - name: Configure AWS credentials
-      #   uses: aws-actions/configure-aws-credentials@v2
-      #   with:
-      #     role-to-assume: ${{ secrets.AWS_SROPHE_ROLE }}
-      #     aws-region: us-east-1
-      #     role-session-name: GitHub-OIDC-data
-      #     role-duration-seconds: 14400
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          role-to-assume: ${{ secrets.AWS_SROPHE_ROLE }}
+          aws-region: us-east-1
+          role-session-name: GitHub-OIDC-data
+          role-duration-seconds: 14400
           
       
-      # - name: Upload HTML files to S3 in parallel(Strip before syriacadata, Map Prefixes, Strip .html)
-      #   run: |
-      #     mkdir -p logs
-      #     > logs/uploaded_files.txt
-      #     html_count=$(find ./data-html -path "*/syriacadata/*.html" | wc -l)
-      #     echo "$html_count" > logs/html_created_count.log
+      - name: Upload HTML files to S3 in parallel(Strip before syriacadata, Map Prefixes, Strip .html)
+        run: |
+          mkdir -p logs
+          > logs/uploaded_files.txt
+          html_count=$(find ./data-html -path "*/syriacadata/*.html" | wc -l)
+          echo "$html_count" > logs/html_created_count.log
           
-      #     find ./data-html -path "*/syriacadata/*.html" -print0 | \
-      #     xargs -0 -P $(nproc) -I {} sh -c '
-      #       set +e
-      #       html_file="$1"
-      #       # Extract the part of the path after "syriacadata/"
-      #       s3_key=$(echo "$html_file" | sed -E "s|^.*?/syriacadata/||" | sed "s/\.html$//")
-      #       # Map top-level dir if needed, for joe files
-      #       top_dir=$(echo "$s3_key" | cut -d/ -f1)
-      #       case "$top_dir" in
-      #         bibl) mapped_dir="cbss" ;;
-      #         subject) mapped_dir="taxonomy" ;;
-      #         *) mapped_dir="$top_dir" ;;
-      #       esac
+          find ./data-html -path "*/syriacadata/*.html" -print0 | \
+          xargs -0 -P $(nproc) -I {} sh -c '
+            set +e
+            html_file="$1"
+            # Extract the part of the path after "syriacadata/"
+            s3_key=$(echo "$html_file" | sed -E "s|^.*?/syriacadata/||" | sed "s/\.html$//")
+            # Map top-level dir if needed, for joe files
+            top_dir=$(echo "$s3_key" | cut -d/ -f1)
+            case "$top_dir" in
+              bibl) mapped_dir="cbss" ;;
+              subject) mapped_dir="taxonomy" ;;
+              *) mapped_dir="$top_dir" ;;
+            esac
       
-      #       rest_of_path=$(echo "$s3_key" | cut -d/ -f2-)
-      #       if [ "$rest_of_path" = "$s3_key" ]; then
-      #         new_key="$mapped_dir"
-      #       else
-      #         new_key="${mapped_dir}/${rest_of_path}"
-      #       fi
+            rest_of_path=$(echo "$s3_key" | cut -d/ -f2-)
+            if [ "$rest_of_path" = "$s3_key" ]; then
+              new_key="$mapped_dir"
+            else
+              new_key="${mapped_dir}/${rest_of_path}"
+            fi
 
-      #       # Get the filename (last segment, like "2")
-      #       filename=$(basename "$s3_key")
-      #       echo "filename: ${filename}"
-      #       # Get the type (first segment after johnofephesus/ if present)
-      #       if echo "$s3_key" | grep -q "^johnofephesus/"; then
-      #         type=$(echo "$s3_key" | sed -E "s|^johnofephesus/([^/]+).*|\1|")
-      #       elif echo "$s3_key" | grep -q "^cbss/"; then
-      #         type="bibl"
-      #       else
-      #         type=$(echo "$s3_key" | cut -d/ -f1)
-      #         type="${type}s"
-      #       fi
+            # Get the filename (last segment, like "2")
+            filename=$(basename "$s3_key")
+            echo "filename: ${filename}"
+            # Get the type (first segment after johnofephesus/ if present)
+            if echo "$s3_key" | grep -q "^johnofephesus/"; then
+              type=$(echo "$s3_key" | sed -E "s|^johnofephesus/([^/]+).*|\1|")
+            elif echo "$s3_key" | grep -q "^cbss/"; then
+              type="bibl"
+            else
+              type=$(echo "$s3_key" | cut -d/ -f1)
+              type="${type}s"
+            fi
 
-      #     # Determine path to original XML (always from canonical path)
-      #       xml_path="./data/${type}/tei/${filename}.xml"
-      #       s3_path="s3://srophe-syriaca-front-end/${new_key}"
-      #       tei_s3_path="s3://srophe-syriaca-front-end/${new_key}.xml"
+          # Determine path to original XML (always from canonical path)
+            xml_path="./data/${type}/tei/${filename}.xml"
+            s3_path="s3://srophe-syriaca-front-end/${new_key}"
+            tei_s3_path="s3://srophe-syriaca-front-end/${new_key}.xml"
 
-      #       echo "Uploading $html_file to $s3_path"
-      #       if aws s3 cp "$html_file" "$s3_path"; then
-      #         echo "$s3_path" >> logs/uploaded_files.txt
-      #       else
-      #         echo "::warning:: Failed to upload $html_file to $s3_path" >> logs/errors.log
-      #       fi
-      #       echo "Uploading $xml_path to $tei_s3_path"
-      #       if aws s3 cp "$xml_path" "$tei_s3_path"; then
-      #         echo "$tei_s3_path" >> logs/uploaded_files.txt
-      #       else
-      #         echo "::warning:: Failed to upload $xml_path to $tei_s3_path" >> logs/errors.log
-      #       fi
-      #       set -e
-      #     ' sh {}
-      #       echo "HTML files created: $(cat logs/html_created_count.log)"
-      #       echo "HTML files uploaded: $(grep -v '\.xml$' logs/uploaded_files.txt | wc -l)"
-      #   env:
-      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-      #     AWS_REGION: ${{ secrets.AWS_REGION }}
+            echo "Uploading $html_file to $s3_path"
+            if aws s3 cp "$html_file" "$s3_path"; then
+              echo "$s3_path" >> logs/uploaded_files.txt
+            else
+              echo "::warning:: Failed to upload $html_file to $s3_path" >> logs/errors.log
+            fi
+            echo "Uploading $xml_path to $tei_s3_path"
+            if aws s3 cp "$xml_path" "$tei_s3_path"; then
+              echo "$tei_s3_path" >> logs/uploaded_files.txt
+            else
+              echo "::warning:: Failed to upload $xml_path to $tei_s3_path" >> logs/errors.log
+            fi
+            set -e
+          ' sh {}
+            echo "HTML files created: $(cat logs/html_created_count.log)"
+            echo "HTML files uploaded: $(grep -v '\.xml$' logs/uploaded_files.txt | wc -l)"
+        env:
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
 
 
       # Step 9: Upload error logs as an artifact for debugging
