commit changes to abstract to opensearch

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,34 +66,34 @@ jobs:
         run: |
           find ./data/persons/tei -name '*.xml' | head -n 25 > xml_files.txt
           find ./data/places/tei -name '*.xml' | head -n 25 >> xml_files.txt
-          # find ./data/works/tei -name '*.xml' | head -n 25 >> xml_files.txt
+          find ./data/works/tei -name '*.xml' | head -n 25 >> xml_files.txt
           # find ./data/bibl/tei -name '*.xml' | head -n 25 >> xml_files.txt
           # find ./data/subjects/tei -name '*.xml' | head -n 25 >> xml_files.txt
           echo "./data/persons/tei/10.xml" >> xml_files.txt
           echo "./data/persons/tei/25.xml" >> xml_files.txt
-          # echo "./data/persons/tei/110.xml" >> xml_files.txt
-          # echo "./data/persons/tei/106.xml" >> xml_files.txt
-          # echo "./data/persons/tei/109.xml" >> xml_files.txt
-          # echo "./data/persons/tei/101.xml" >> xml_files.txt
-          # echo "./data/persons/tei/100.xml" >> xml_files.txt
-          # echo "./data/persons/tei/102.xml" >> xml_files.txt
-          # echo "./data/persons/tei/1021.xml" >> xml_files.txt
-          # echo "./data/persons/tei/320.xml" >> xml_files.txt
-          # echo "./data/persons/tei/67.xml" >> xml_files.txt
-          # echo "./data/persons/tei/544.xml" >> xml_files.txt
-          # echo "./data/persons/tei/732.xml" >> xml_files.txt
+          echo "./data/persons/tei/110.xml" >> xml_files.txt
+          echo "./data/persons/tei/106.xml" >> xml_files.txt
+          echo "./data/persons/tei/109.xml" >> xml_files.txt
+          echo "./data/persons/tei/101.xml" >> xml_files.txt
+          echo "./data/persons/tei/100.xml" >> xml_files.txt
+          echo "./data/persons/tei/102.xml" >> xml_files.txt
+          echo "./data/persons/tei/1021.xml" >> xml_files.txt
+          echo "./data/persons/tei/320.xml" >> xml_files.txt
+          echo "./data/persons/tei/67.xml" >> xml_files.txt
+          echo "./data/persons/tei/544.xml" >> xml_files.txt
+          echo "./data/persons/tei/732.xml" >> xml_files.txt
           echo "./data/places/tei/10.xml" >> xml_files.txt
-          # echo "./data/places/tei/78.xml" >> xml_files.txt
-          # echo "./data/places/tei/1507.xml" >> xml_files.txt
-          # echo "./data/places/tei/1486.xml" >> xml_files.txt
-          # echo "./data/places/tei/104.xml" >> xml_files.txt
-          # echo "./data/places/tei/602.xml" >> xml_files.txt
-          # echo "./data/works/tei/315.xml" >> xml_files.txt
-          # echo "./data/works/tei/9501.xml" >> xml_files.txt
-          # echo "./data/works/tei/nhsl/tei/9723.xml" >> xml_files.txt
-          # echo "./data/works/tei/nhsl/tei/9724.xml" >> xml_files.txt
-          # echo "./data/works/tei/10510.xml" >> xml_files.txt
-          # echo "./data/works/tei/nhsl/tei/10511.xml" >> xml_files.txt 
+          echo "./data/places/tei/78.xml" >> xml_files.txt
+          echo "./data/places/tei/1507.xml" >> xml_files.txt
+          echo "./data/places/tei/1486.xml" >> xml_files.txt
+          echo "./data/places/tei/104.xml" >> xml_files.txt
+          echo "./data/places/tei/602.xml" >> xml_files.txt
+          echo "./data/works/tei/315.xml" >> xml_files.txt
+          echo "./data/works/tei/9501.xml" >> xml_files.txt
+          echo "./data/works/tei/nhsl/tei/9723.xml" >> xml_files.txt
+          echo "./data/works/tei/nhsl/tei/9724.xml" >> xml_files.txt
+          echo "./data/works/tei/10510.xml" >> xml_files.txt
+          echo "./data/works/tei/nhsl/tei/10511.xml" >> xml_files.txt 
           # echo "Processing specified XML files:"
           
           cat xml_files.txt   
@@ -194,23 +194,23 @@ jobs:
 
       # Step 8: Upload JSON data to OpenSearch 
 
-      # - name: JSON file to OpenSearch
+      - name: JSON file to OpenSearch
 
-      #   env:
-      #     OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
-      #     OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
-      #     OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
-      #   run: |
-      #     RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
-      #     -H "Content-Type: application/json" \
-      #     -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
-      #     --data-binary "@bulk_data.json")
-      #     echo "HTTP response code: $RESPONSE"
-      #     cat response.json
+        env:
+          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
+          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
+          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
+        run: |
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
+          -H "Content-Type: application/json" \
+          -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
+          --data-binary "@bulk_data.json")
+          echo "HTTP response code: $RESPONSE"
+          cat response.json
 
-      #     # Check for errors in the response
-      #     if grep -q '"errors":true' response.json; then
-      #       echo "Errors occurred during bulk upload"
-      #       exit 1
-      #     fi
+          # Check for errors in the response
+          if grep -q '"errors":true' response.json; then
+            echo "Errors occurred during bulk upload"
+            exit 1
+          fi
 
