debug messaging for syriaca repo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -151,6 +151,13 @@ jobs:
             # Run the XSLT transformation located in the siteGenerator of syriaca repository
 
             java -jar saxon.jar -s:$file -xsl:syriaca/siteGenerator/xsl/staticHTML.xsl -o:data-html/${type}/${filename}.html dataPath=./data/ 2> error.log
+            # verify that html is created with syriaca repository resource
+            if [ -f data-html/${type}/${filename}.html ]; then
+              echo "✅ Successfully created: data-html/${type}/${filename}.html"
+            else
+              echo "❌ Failed to create: data-html/${type}/${filename}.html"
+              exit 1
+            fi
 
             # Run the XSLT transformation located in the root of syriaca-data repository
             
