Update main.yml
Test OpenSearch bibl

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,18 +53,19 @@ jobs:
       #     echo "Updated XML files: $UPDATED_FILES"
       #     echo "::set-output name=updated_files::$UPDATED_FILES"
       #   id: files
+      
       # Step 4: Identify the first 5 XML files for testing
       - name: Identify first 5 XML files 
         run: |
           find ./data/bibl/tei -name '*.xml' | head -n 5 > xml_files.txt
           echo "Processing the first 5 XML files:"
           cat xml_files.txt
-          
 
       # Step 5: Run XSLT Transformations and Merge into Single JSON 
       - name: Run XSLT Transformations and Create Bulk JSON
         run: |
           touch bulk_data.json  # Create the bulk JSON file
+          # Commented out code in this section for possible optimization of code
           # mkdir -p data-html
           # echo "Created HTML directory"
           
@@ -154,7 +155,7 @@ jobs:
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           
-# - name: Install aws-es-curl
+# - name: Install aws-es-curl #Need V4 Authentication?
 #   run: |
 #     sudo apt-get update
 #     sudo apt-get install -y libwww-perl libcrypt-ssleay-perl
@@ -172,26 +173,26 @@ jobs:
 
           
 
-      # - name: JSON file to OpenSearch
-      #   run: |
-      #     curl -X POST "${OPENSEARCH_URL}/_bulk" \
-      #     -H "Content-Type: application/json" \
-      #     --data-binary "@bulk_data.json"
-        # env:
-        #   OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
-        #   OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
-        #   OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
+      - name: JSON file to OpenSearch
         # run: |
-        #   RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
+        #   curl -X POST "${OPENSEARCH_URL}/_bulk" \
         #   -H "Content-Type: application/json" \
-        #   -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
-        #   --data-binary "@bulk_data.json")
-        #   echo "HTTP response code: $RESPONSE"
-        #   cat response.json
+        #   --data-binary "@bulk_data.json"
+        env:
+          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
+          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
+          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
+        run: |
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
+          -H "Content-Type: application/json" \
+          -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
+          --data-binary "@bulk_data.json")
+          echo "HTTP response code: $RESPONSE"
+          cat response.json
 
-        #   # Check for errors in the response
-        #   if grep -q '"errors":true' response.json; then
-        #     echo "Errors occurred during bulk upload"
-        #     exit 1
-        #   fi
+          # Check for errors in the response
+          if grep -q '"errors":true' response.json; then
+            echo "Errors occurred during bulk upload"
+            exit 1
+          fi
 
