update for index 4

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,22 +61,6 @@ jobs:
       #     echo "Processing 25 XML files:"
       #     cat xml_files.txt
 
-      # - name: Specify specific Person XML files
-      #   run: |
-      #     echo "./data/persons/tei/25.xml" > xml_files.txt
-      #     echo "./data/persons/tei/110.xml" > xml_files.txt
-      #     echo "./data/persons/tei/106.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/109.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/101.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/100.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/102.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/1021.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/320.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/67.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/544.xml" >> xml_files.txt
-      #     echo "./data/persons/tei/732.xml" >> xml_files.txt
-      #     echo "Processing specified XML files:"
-      #     cat xml_files.txt
       
       - name: Specify specific XML files and 25 per category 
         run: |
@@ -114,16 +98,6 @@ jobs:
           
           cat xml_files.txt   
           
-      # - name: Specify specific Works XML files
-      #   run: |
-      #     echo "./data/works/tei/315.xml" > xml_files.txt
-      #     echo "./data/works/tei/9501.xml" >> xml_files.txt
-      #     echo "./data/works/tei/nhsl/tei/9723.xml" >> xml_files.txt
-      #     echo "./data/works/tei/nhsl/tei/9724.xml" >> xml_files.txt
-      #     echo "./data/works/tei/10510.xml" >> xml_files.txt
-      #     echo "./data/works/tei/nhsl/tei/10511.xml" >> xml_files.txt 
-      #     echo "Processing specified XML files:"
-      #     cat xml_files.txt   
 
       # Step 5: Run XSLT Transformations and Merge into Single JSON 
       - name: Run XSLT Transformations and Create Bulk JSON
@@ -145,7 +119,7 @@ jobs:
             # Extract the filename and create the index header for OpenSearch bulk format
             filename=$(basename ${file%.xml})
             echo "Processing $filename for JSON"
-            printf "{\"index\":{\"_index\":\"syriaca-index-3\",\"_id\":\"$type-$filename\"}}\n" >> bulk_data.json
+            printf "{\"index\":{\"_index\":\"syriaca-index-4\",\"_id\":\"$type-$filename\"}}\n" >> bulk_data.json
       
             # Apply XSLT for JSON conversion and append it to bulk_data.json directly
             java -jar saxon.jar -s:$file -xsl:json-stylesheet.xsl docType="$type" | tr -d '\n' >> bulk_data.json
@@ -220,23 +194,23 @@ jobs:
 
       # Step 8: Upload JSON data to OpenSearch 
 
-      - name: JSON file to OpenSearch
+      # - name: JSON file to OpenSearch
 
-        env:
-          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
-          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
-          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
-        run: |
-          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
-          -H "Content-Type: application/json" \
-          -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
-          --data-binary "@bulk_data.json")
-          echo "HTTP response code: $RESPONSE"
-          cat response.json
+      #   env:
+      #     OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
+      #     OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
+      #     OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
+      #   run: |
+      #     RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
+      #     -H "Content-Type: application/json" \
+      #     -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
+      #     --data-binary "@bulk_data.json")
+      #     echo "HTTP response code: $RESPONSE"
+      #     cat response.json
 
-          # Check for errors in the response
-          if grep -q '"errors":true' response.json; then
-            echo "Errors occurred during bulk upload"
-            exit 1
-          fi
+      #     # Check for errors in the response
+      #     if grep -q '"errors":true' response.json; then
+      #       echo "Errors occurred during bulk upload"
+      #       exit 1
+      #     fi
 
