test pubDate error handling

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,8 +4,8 @@ on:
   push:
     branches:
       - 'development_backup_cbss-bibls'  # current data branch
-    paths:
-      - 'data/**'  # Trigger only on changes to data files   
+    # paths:
+    #   - 'data/**'  # Trigger only on changes to data files   
       
 permissions:
   id-token: write
@@ -82,8 +82,7 @@ jobs:
       - name: Identify XML files 
         run: |
           # find ./data/places/tei -name '*.xml' | head -n 10 > xml_files.txt
-          find ./data/bibl/tei -name '*.xml' | tail -n +15027 | head -n 5000 > xml_files.txt
-          # find ./data/bibl/tei -name '*.xml' > xml_files.txt
+          find ./data/bibl/tei -name '*.xml' > xml_files.txt
           echo "Processing XML files:"
           cat xml_files.txt
           
@@ -196,35 +195,35 @@ jobs:
 
       # Step 8: Upload JSON data to OpenSearch 
 
-      - name: JSON file to OpenSearch
+      # - name: JSON file to OpenSearch
 
-        env:
-          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
-          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
-          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
-        run: |
-          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
-          -H "Content-Type: application/json" \
-          -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
-          --data-binary "@bulk_data.json")
-          echo "HTTP response code: $RESPONSE"
-          cat response.json
+      #   env:
+      #     OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
+      #     OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
+      #     OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
+      #   run: |
+      #     RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
+      #     -H "Content-Type: application/json" \
+      #     -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
+      #     --data-binary "@bulk_data.json")
+      #     echo "HTTP response code: $RESPONSE"
+      #     cat response.json
 
-          # Check for errors in the response
-          if grep -q '"errors":true' response.json; then
-            echo "Errors occurred during bulk upload"
-            exit 1
-          fi
+      #     # Check for errors in the response
+      #     if grep -q '"errors":true' response.json; then
+      #       echo "Errors occurred during bulk upload"
+      #       exit 1
+      #     fi
 
-          # Parse the response for failed items using jq
-          FAILED_ENTRIES=$(jq -c '.items[] | select(.index.status >= 400) | {id: .index._id, error: .index.error}' response.json)
+      #     # Parse the response for failed items using jq
+      #     FAILED_ENTRIES=$(jq -c '.items[] | select(.index.status >= 400) | {id: .index._id, error: .index.error}' response.json)
           
-          if [[ -n "$FAILED_ENTRIES" ]]; then
-            echo "Failed entries:"
-            echo "$FAILED_ENTRIES" > failed_entries.json
-            echo "$FAILED_ENTRIES" # Prints to the console
-          else
-            echo "All entries were successfully indexed."
-          fi
+      #     if [[ -n "$FAILED_ENTRIES" ]]; then
+      #       echo "Failed entries:"
+      #       echo "$FAILED_ENTRIES" > failed_entries.json
+      #       echo "$FAILED_ENTRIES" # Prints to the console
+      #     else
+      #       echo "All entries were successfully indexed."
+      #     fi
 
 
