Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,15 +63,15 @@ jobs:
       - name: Run XSLT Transformations and Create Bulk JSON
         run: |
           touch bulk_data.json  # Create the bulk JSON file
-          mkdir -p data-html
-          echo "Created HTML directory"
+          # mkdir -p data-html
+          # echo "Created HTML directory"
           
           while IFS= read -r file; do
             echo "Processing $file"
       
             # Extract the document type from the file path
             type=$(echo "$file" | grep -o -E 'work|subject|person|place|spear|bibl')
-      
+            echo "type $type"
             # Extract the filename and create the index header for OpenSearch bulk format
             filename=$(basename ${file%.xml})
             echo "Processing $filename for JSON"
@@ -85,18 +85,18 @@ jobs:
             # java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:- | \
             # aws s3 cp - s3://srophe-syriaca-front-end/${type}/${filename}.html
             # Apply XSLT for HTML conversion and capture any error
-            echo "Processing $file for HTML $filename"
-            java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/$(basename ${file%.xml}.html) 2>&1 | tee saxon_error.log
+            # echo "Processing $file for HTML $filename"
+            # java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/${filename}.html 2>&1 | tee saxon_error.log
   
-            # Check if the HTML file was created
-            if [ ! -f "data-html/${filename}.html" ]; then
-              echo "Error: HTML file for $filename was not created."
-              cat saxon_error.log
-              exit 1
-            fi
+            # # Check if the HTML file was created
+            # if [ ! -f "data-html/${filename}.html" ]; then
+            #   echo "Error: HTML file for $filename was not created."
+            #   cat saxon_error.log
+            #   exit 1
+            # fi
 
-            # Upload the HTML file to S3
-            aws s3 cp data-html/$(basename ${file%.xml}.html) s3://srophe-syriaca-front-end/${type}/${filename}.html
+            # # Upload the HTML file to S3
+            # aws s3 cp data-html/$(basename ${file%.xml}.html) s3://srophe-syriaca-front-end/${type}/${filename}.html
   
 
           done < xml_files.txt
@@ -107,25 +107,25 @@ jobs:
      
           
           
-      # Step 5: Create a directory for static HTML files (staticSitePath)
-      # - name: Create static HTML directory
-      #   run: |
-      #     mkdir -p data-html  # staticSitePath in html-stylesheet
-      #     echo "Created HTML directory"
+      # Step 5: Create a directory for static HTML files 
+      - name: Create static HTML directory
+        run: |
+          mkdir -p data-html  
+          echo "Created HTML directory"
 
-      # Step 6
-      # - name: Run XSLT Transformations for HTML
-      #   run: |
-      #     while IFS= read -r file; do
-      #       echo "Processing $file for HTML"
-      #       # Extract the document type from the file path
-      #       type=$(echo "$file" | grep -o -E 'work|subject|person|place|spear|bibl')
+     
+      - name: Run XSLT Transformations for HTML
+        run: |
+          while IFS= read -r file; do
+            echo "Processing $file for HTML"
+            # Extract the document type from the file path
+            type=$(echo "$file" | grep -o -E 'work|subject|person|place|spear|bibl')
       
-      #       # Extract the filename and create the index header for OpenSearch bulk format
-      #       filename=$(basename ${file%.xml})
-      #       # Run the XSLT transformation located in the root of syriaca-data repository
-      #       java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/$(basename ${file%.xml}.html)
-      #     done < xml_files.txt
+            # Extract the filename and create the index header for OpenSearch bulk format
+            filename=$(basename ${file%.xml})
+            # Run the XSLT transformation located in the root of syriaca-data repository
+            java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/$(basename ${file%.xml}.html)
+          done < xml_files.txt
           
        
       # Step 6: Upload files to S3 
@@ -136,14 +136,14 @@ jobs:
           AWS_REGION: ${{ secrets.AWS_REGION }}
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 
-      # - name: Upload HTML files to S3
-      #   run: |
-      #     for html_file in $(find ./data-html -name "*.html"); do
-      #       aws s3 cp $html_file s3://srophe-syriaca-front-end/testHtml/$(basename $html_file)
-      #     done
-      #   env:
-      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-      #     AWS_REGION: ${{ secrets.AWS_REGION }}
+      - name: Upload HTML files to S3
+        run: |
+          for html_file in $(find ./data-html -name "*.html"); do
+            aws s3 cp $html_file s3://srophe-syriaca-front-end/testHtml/$(basename $html_file)
+          done
+        env:
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
 
       # - name: JSON file to OpenSearch
       #   run: |
