set workflow file to convert and deploy any changes to data files only

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,8 +4,8 @@ on:
   push:
     branches:
       - 'development_backup_cbss-bibls'  # current data branch
-    # paths:
-    #   - 'data/**'  # Trigger only on changes to data files   
+    paths:
+      - 'data/**'  # Trigger only on changes to data files   
       
 permissions:
   id-token: write
@@ -47,30 +47,19 @@ jobs:
           role-session-name: GitHub-OIDC-data    
           
       # Step 4: Find updated XML files
-      # - name: Identify updated XML files
-      #   run: |
-      #     UPDATED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '.xml')
-      #     echo "Updated XML files: $UPDATED_FILES"
-      #     echo "::set-output name=updated_files::$UPDATED_FILES"
-      #   id: files
+      - name: Identify updated XML files
+        run: |
+          UPDATED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '.xml')
+          echo "Updated XML files: $UPDATED_FILES"
+          echo "::set-output name=updated_files::$UPDATED_FILES"
+        id: files
       
-      # Step 4: Identify 25 XML files for testing
-      # - name: Identify 25 XML files 
+      # Step 4: Identify XML files for testing
+      # - name: Identify XML files 
       #   run: |
-      #     find ./data/persons/tei -name '*.xml' | head -n 25 > xml_files.txt
+      #     find ./data/persons/tei -name '*.xml' > xml_files.txt
       #     echo "Processing 25 XML files:"
       #     cat xml_files.txt
-
-      
-      - name: Specify specific XML files and 25 per category 
-        run: |
-          # find ./data/persons/tei -name '*.xml' | tail -n +26 > xml_files.txt
-          # find ./data/places/tei -name '*.xml' | tail -n +26 >> xml_files.txt
-          # find ./data/works/tei -name '*.xml' | head -n 25 >> xml_files.txt
-          find ./data/bibl/tei -name '*.xml' | tail -n +20027 | head -n 10000 > xml_files.txt
-          # find ./data/subjects/tei -name '*.xml' | tail -n +26 > xml_files.txt
-          
-          cat xml_files.txt   
           
 
       # Step 5: Run XSLT Transformations and Merge into Single JSON 
@@ -82,17 +71,15 @@ jobs:
           # echo "Created HTML directory"
           
           while IFS= read -r file; do
-            # echo "Processing $file"
       
             # Extract the document type from the file path
             type=$(echo "$file" | grep -o -E 'work|subject|person|place|bibl')
-            # Prioritize 'subject' over other types
+            # Fix bible/subject/worker conflict: choose 'subject' over other types
             if [[ "$type" == *"subject"* ]]; then
               type="subject"
             elif [[ "$type" == *"bibl"* ]]; then
               type="cbss"
             fi
-            echo "Json type $type"
             # Extract the filename and create the index header for OpenSearch bulk format
             filename=$(basename ${file%.xml})
             echo "Processing $filename for JSON"
@@ -113,31 +100,31 @@ jobs:
           AWS_REGION: ${{ secrets.AWS_REGION }}          
 
       # Step 6: Convert HTML files
-      # - name: Create static HTML directory
-      #   run: |
-      #     mkdir -p data-html  
-      #     echo "Created HTML directory"
+      - name: Create static HTML directory
+        run: |
+          mkdir -p data-html  
+          echo "Created HTML directory"
 
      
-      # - name: Run XSLT Transformations for HTML
-      #   run: |
-      #     while IFS= read -r file; do
-      #       echo "Processing $file for HTML"
-      #       # Extract the document type from the file path
-      #       type=$(echo "$file" | grep -o -E 'work|subject|person|place|bibl' | tail -n 1)
-      #       # Extract the filename and create the index header for OpenSearch bulk format
-      #       filename=$(basename ${file%.xml})
-      #       echo "html filename: $filename"
-      #       # if [ "$type" == "bibl" ]; then
-      #       #   type="cbss"
-      #       # fi
-      #       echo "HTML type $type"
+      - name: Run XSLT Transformations for HTML
+        run: |
+          while IFS= read -r file; do
+            echo "Processing $file for HTML"
+            # Extract the document type from the file path
+            type=$(echo "$file" | grep -o -E 'work|subject|person|place|bibl' | tail -n 1)
+            # Extract the filename and create the index header for OpenSearch bulk format
+            filename=$(basename ${file%.xml})
+            echo "html filename: $filename"
+            # if [ "$type" == "bibl" ]; then
+            #   type="cbss"
+            # fi
+            echo "HTML type $type"
 
-      #       # Run the XSLT transformation located in the root of syriaca-data repository
-      #       java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/${type}/${filename}.html
-      #       # java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/${filename}.html
+            # Run the XSLT transformation located in the root of syriaca-data repository
+            java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/${type}/${filename}.html
+            # java -jar saxon.jar -s:$file -xsl:html-stylesheet.xsl -o:data-html/${filename}.html
 
-      #     done < xml_files.txt
+          done < xml_files.txt
 
       # Step 6: 
       - name: Configure AWS credentials from AWS account
@@ -151,63 +138,63 @@ jobs:
       # Step 7: Upload files to S3 
       - name: Upload JSON file to S3 
         run: |
-          aws s3 cp bulk_data.json s3://srophe-syriaca-front-end/json-data/advancedsearchfields/bulk_data_index_8_bibl_20000.json
+          aws s3 cp bulk_data.json s3://srophe-syriaca-front-end/json-data/advancedsearchfields/bulk_data_index_8_data_update.json
         env:
           AWS_REGION: ${{ secrets.AWS_REGION }}
           AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
 
-      # - name: Upload HTML files to S3
-      #   run: |
+      - name: Upload HTML files to S3
+        run: |
         
-      #     for html_file in $(find ./data-html -name "*.html"); do
-      #       type=$(echo "$html_file" | grep -o -E 'work|subject|person|place|bibl' | tail -n 1)
-      #       echo "html_file $html_file"
-      #       if [ "$type" == "subject" ]; then
-      #         type="taxonomy"
-      #       fi
-      #       if [ "$type" == "bibl" ]; then
-      #         type="cbss"
-      #       fi
-      #       # Copy html file to S3 with the idno path
-      #       aws s3 cp $html_file s3://srophe-syriaca-front-end/${type}/$(basename ${html_file%.html})
-      #     done
+          for html_file in $(find ./data-html -name "*.html"); do
+            type=$(echo "$html_file" | grep -o -E 'work|subject|person|place|bibl' | tail -n 1)
+            echo "html_file $html_file"
+            if [ "$type" == "subject" ]; then
+              type="taxonomy"
+            fi
+            if [ "$type" == "bibl" ]; then
+              type="cbss"
+            fi
+            # Copy html file to S3 with the idno path
+            aws s3 cp $html_file s3://srophe-syriaca-front-end/${type}/$(basename ${html_file%.html})
+          done
           
-      #   env:
-      #     AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-      #     AWS_REGION: ${{ secrets.AWS_REGION }}
+        env:
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
 
 
       # Step 8: Upload JSON data to OpenSearch 
 
-      # - name: JSON file to OpenSearch
+      - name: JSON file to OpenSearch
 
-      #   env:
-      #     OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
-      #     OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
-      #     OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
-      #   run: |
-      #     RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
-      #     -H "Content-Type: application/json" \
-      #     -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
-      #     --data-binary "@bulk_data.json")
-      #     echo "HTTP response code: $RESPONSE"
-      #     cat response.json
+        env:
+          OPENSEARCH_URL: ${{ secrets.OPENSEARCH_URL }}
+          OPENSEARCH_USER: ${{ secrets.OPENSEARCH_USER }}
+          OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
+        run: |
+          RESPONSE=$(curl -s -o response.json -w "%{http_code}" -XPOST "$OPENSEARCH_URL/_bulk" \
+          -H "Content-Type: application/json" \
+          -u "$OPENSEARCH_USER:$OPENSEARCH_PASSWORD" \
+          --data-binary "@bulk_data.json")
+          echo "HTTP response code: $RESPONSE"
+          cat response.json
 
           # Check for errors in the response
-          # if grep -q '"errors":true' response.json; then
-          #   echo "Errors occurred during bulk upload"
-          #   exit 1
-          # fi
+          if grep -q '"errors":true' response.json; then
+            echo "Errors occurred during bulk upload"
+            exit 1
+          fi
 
           # Parse the response for failed items using jq
-          # FAILED_ENTRIES=$(jq -c '.items[] | select(.index.status >= 400) | {id: .index._id, error: .index.error}' response.json)
+          FAILED_ENTRIES=$(jq -c '.items[] | select(.index.status >= 400) | {id: .index._id, error: .index.error}' response.json)
           
-          # if [[ -n "$FAILED_ENTRIES" ]]; then
-          #   echo "Failed entries:"
-          #   echo "$FAILED_ENTRIES" > failed_entries.json
-          #   echo "$FAILED_ENTRIES" # Prints to the console
-          # else
-          #   echo "All entries were successfully indexed."
-          # fi
+          if [[ -n "$FAILED_ENTRIES" ]]; then
+            echo "Failed entries:"
+            echo "$FAILED_ENTRIES" > failed_entries.json
+            echo "$FAILED_ENTRIES" # Prints to the console
+          else
+            echo "All entries were successfully indexed."
+          fi
 
 
